project_id = "nqzreyydyirslxdtfuna"

[functions.upload-template]
verify_jwt = false

[functions.download-template]
verify_jwt = false

[functions.delete-template]
verify_jwt = false

[functions.mds-import]
verify_jwt = false

[functions.pdf-fetch]
verify_jwt = false

[functions.process-generation]
verify_jwt = false

[functions.generate-forms]
verify_jwt = false

[functions.list-exports]
verify_jwt = false

[functions.upload-export]
verify_jwt = false

[functions.check-bpmn]
verify_jwt = false
